// Differential tests (ADR-004): every TypeScript port against the golden
// fixtures generated by the Python original (tools/fixtures/gen_fixtures.py).
// A port passes when its worst relative difference over every fixture value
// is within the module's tolerance, which the fixture file itself carries.
import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { Cam, SliderCrank, type CamSpec, type CrankGeometry } from "../src/kinematics.js";
import * as thermo from "../src/thermo.js";
import { FrictionModel, type EngineView } from "../src/friction.js";
import { Oil } from "../src/lubrication.js";

const here = path.dirname(fileURLToPath(import.meta.url));
// compiled to dist/test/, fixtures live beside src/
const FIXTURES = path.resolve(here, "..", "..", "fixtures");

const results: [string, boolean][] = [];
const check = (name: string, ok: boolean, note = "") => {
  results.push([name, ok]);
  console.log(`${ok ? "PASS" : "FAIL"}  ${name}${note ? "  -- " + note : ""}`);
};

interface Fixture<I, O> {
  meta: { module: string; tolerance_rel: number; physics_hash: string; numpy: string };
  inputs: I;
  outputs: O;
}
function load<I, O>(name: string): Fixture<I, O> {
  return JSON.parse(readFileSync(path.join(FIXTURES, `${name}.json`), "utf8")) as Fixture<I, O>;
}

/**
 * Worst relative difference of `got` against `want`, the same definition as
 * gen_fixtures.py's compare(): the denominator is floored at 1e-3 of the
 * largest |value| in the series, so zero crossings do not divide by zero.
 */
export function worstRel(got: readonly number[], want: readonly number[]): { rel: number; at: number } {
  if (got.length !== want.length) return { rel: Infinity, at: -1 };
  let big = 0;
  for (const w of want) big = Math.max(big, Math.abs(w));
  const floor = Math.max(1e-3 * big, 1e-300);
  let rel = 0, at = 0;
  for (let i = 0; i < want.length; i++) {
    const r = Math.abs(got[i]! - want[i]!) / Math.max(Math.abs(want[i]!), floor);
    if (Number.isNaN(r)) return { rel: Infinity, at: i }; // NaN is the worst there is
    if (r > rel) { rel = r; at = i; }
  }
  return { rel, at };
}

class Worst {
  rel = 0;
  where = "";
  add(where: string, got: readonly number[], want: readonly number[]) {
    const w = worstRel(got, want);
    if (w.rel > this.rel) { this.rel = w.rel; this.where = `${where}[${w.at}]`; }
  }
}

/**
 * Finite-difference outputs are compared at the rounding bound propagated
 * through the ORIGINAL's stencil, not at the module tolerance. A lift
 * sample may differ by up to 4 ulp of lift_max between two libms: 1 ulp in
 * sin, doubled by the square, plus the square's and the lift_max multiply's
 * own roundings. So the central first difference over 2h can differ by
 * 2*4*eps*Lmax/(2h) and the 1,-2,1 second difference by (1+2+1)*4*eps*Lmax/h^2.
 * Near an inflection that is ~1e-10 of the series' largest value, and the
 * same holds between two Python builds on different libms (a first bound of
 * 1 ulp per sample was measured at 1.002 of itself: too tight).
 * Returns the worst |diff| as a fraction of the bound.
 */
function worstFd(got: readonly number[], want: readonly number[], bound: number): { frac: number; at: number } {
  let frac = 0, at = 0;
  for (let i = 0; i < want.length; i++) {
    const f = Math.abs(got[i]! - want[i]!) / bound;
    if (Number.isNaN(f)) return { frac: Infinity, at: i };
    if (f > frac) { frac = f; at = i; }
  }
  return { frac, at };
}
const EPS = 2.220446049250313e-16;

// ------------------------------------------------------------- comparator self-test
// A harness that cannot fail tests nothing: prove it catches a difference
// at the tolerances used here, and NaN, and a length mismatch.
{
  const want = [0, 1e-3, 0.5, 1];
  const tiny = worstRel(want.map((x) => x * (1 + 1e-14)), want).rel;
  const off = worstRel([0, 1e-3, 0.5, 1 + 1e-11], want).rel;
  const nan = worstRel([0, NaN, 0.5, 1], want).rel; // NaN before a 0: must not be overwritten
  const len = worstRel([0, 1], want).rel;
  check("comparator: 1e-14 passes 1e-12, 1e-11 fails it, NaN and length fail",
    tiny <= 1e-12 && off > 1e-12 && !(nan <= 1) && len === Infinity,
    `1e-14 -> ${tiny.toExponential(1)}, 1e-11 -> ${off.toExponential(1)}, NaN -> ${nan}, length -> ${len}`);
}

// ------------------------------------------------------------------ kinematics
{
  type KIn = { theta_rad: number[]; theta_deg: number[]; omega: number[];
    cranks: (CrankGeometry & { name: string })[]; cams: (CamSpec & { name: string })[] };
  type KOut = {
    cranks: Record<"displacement" | "dx_dtheta" | "d2x_dtheta2" | "volume" | "dV_dtheta" | "beta", number[]>[];
    cams: { h_ramp: number; dur: number; lift: number[]; cam_lift: number[]; dlift_dtheta: number[];
      d2lift_dtheta2: number[]; seating_velocity: number[] }[];
  };
  const fx = load<KIn, KOut>("kinematics");
  const w = new Worst();
  const { theta_rad: th, theta_deg: deg } = fx.inputs;
  fx.inputs.cranks.forEach((c, i) => {
    const sc = new SliderCrank(c);
    const o = fx.outputs.cranks[i]!;
    w.add(`${c.name} displacement`, th.map((t) => sc.displacement(t)), o.displacement);
    w.add(`${c.name} dx_dtheta`, th.map((t) => sc.dxDtheta(t)), o.dx_dtheta);
    w.add(`${c.name} d2x_dtheta2`, th.map((t) => sc.d2xDtheta2(t)), o.d2x_dtheta2);
    w.add(`${c.name} volume`, th.map((t) => sc.volume(t)), o.volume);
    w.add(`${c.name} dV_dtheta`, th.map((t) => sc.dVDtheta(t)), o.dV_dtheta);
    w.add(`${c.name} beta`, th.map((t) => sc.beta(t)), o.beta);
  });
  let fdFrac = 0, fdWhere = "";
  fx.inputs.cams.forEach((c, i) => {
    const cam = new Cam(c);
    const o = fx.outputs.cams[i]!;
    w.add(`${c.name} h_ramp/dur`, [cam.hRamp, cam.dur], [o.h_ramp, o.dur]);
    w.add(`${c.name} lift`, deg.map((d) => cam.lift(d)), o.lift);
    w.add(`${c.name} cam_lift`, deg.map((d) => cam.camLift(d)), o.cam_lift);
    w.add(`${c.name} seating_velocity`, fx.inputs.omega.map((om) => cam.seatingVelocity(om)), o.seating_velocity);
    const lmax = c.lift_max, h1 = 0.05 * (Math.PI / 180), h2 = 0.1 * (Math.PI / 180);
    for (const [key, got, bound] of [
      ["dlift_dtheta", deg.map((d) => cam.dliftDtheta(d)), (4 * EPS * lmax) / h1],
      ["d2lift_dtheta2", deg.map((d) => cam.d2liftDtheta2(d)), (16 * EPS * lmax) / h2 ** 2],
    ] as const) {
      const f = worstFd(got, o[key], bound);
      if (f.frac > fdFrac) { fdFrac = f.frac; fdWhere = `${c.name} ${key}[${f.at}]`; }
    }
  });
  const n = fx.inputs.cranks.length * 6 * th.length + fx.inputs.cams.length * (2 * deg.length + 5);
  check("kinematics port matches Python", w.rel <= fx.meta.tolerance_rel,
    `${n} values, worst rel ${w.rel.toExponential(2)} at ${w.where || "-"} (tolerance ${fx.meta.tolerance_rel}), physics ${fx.meta.physics_hash.slice(0, 12)}`);
  check("kinematics finite differences within the stencil's rounding bound", fdFrac <= 1.0,
    `${fx.inputs.cams.length * 2 * deg.length} values, worst ${fdFrac.toFixed(3)} of the bound at ${fdWhere || "-"}`);
}

// ---------------------------------------------------------------------- thermo
{
  type TIn = {
    T: number[]; yb: number[];
    orifice: { p_up: number; T_up: number; p_dn: number; A: number; gamma: number; R: number }[];
    signed: { p1: number; T1: number; yb1: number; p2: number; T2: number; yb2: number; A: number }[];
    valve: { lift: number; dia: number; n: number; cd: number }[];
    u_targets: { u: number; yb: number }[];
    p_T: { p: number; T: number }[];
  };
  type TOut = Record<"cp_air" | "cp_burned" | "gas_R" | "air_viscosity" | "air_density" | "T_from_u"
    | "orifice_mdot" | "valve_effective_area", number[]>
    & Record<"cp_mix" | "gamma_mix" | "u_mix" | "h_mix" | "speed_of_sound" | "signed_orifice", number[][]>;
  const fx = load<TIn, TOut>("thermo");
  const i = fx.inputs, o = fx.outputs, w = new Worst();
  w.add("cp_air", i.T.map(thermo.cpAir), o.cp_air);
  w.add("cp_burned", i.T.map(thermo.cpBurned), o.cp_burned);
  w.add("gas_R", i.yb.map(thermo.gasR), o.gas_R);
  const grid = (f: (T: number, yb: number) => number) => i.yb.map((y) => i.T.map((t) => f(t, y)));
  for (const [name, f] of [["cp_mix", thermo.cpMix], ["gamma_mix", thermo.gammaMix], ["u_mix", thermo.uMix],
    ["h_mix", thermo.hMix], ["speed_of_sound", thermo.speedOfSound]] as const) {
    grid(f).forEach((row, k) => w.add(`${name}[yb ${i.yb[k]}]`, row, o[name][k]!));
  }
  w.add("air_viscosity", i.T.map(thermo.airViscosity), o.air_viscosity);
  w.add("air_density", i.p_T.map((d) => thermo.airDensity(d.p, d.T)), o.air_density);
  w.add("T_from_u", i.u_targets.map((d) => thermo.TFromU(d.u, d.yb)), o.T_from_u);
  w.add("orifice_mdot", i.orifice.map((d) => thermo.orificeMdot(d.p_up, d.T_up, d.p_dn, d.A, d.gamma, d.R)), o.orifice_mdot);
  i.signed.forEach((d, k) => w.add(`signed_orifice[${k}]`,
    thermo.signedOrifice(d.p1, d.T1, d.yb1, d.p2, d.T2, d.yb2, d.A), o.signed_orifice[k]!));
  w.add("valve_effective_area", i.valve.map((d) => thermo.valveEffectiveArea(d.lift, d.dia, d.n, d.cd)), o.valve_effective_area);
  check("thermo port matches Python", w.rel <= fx.meta.tolerance_rel,
    `worst rel ${w.rel.toExponential(2)} at ${w.where || "-"} (tolerance ${fx.meta.tolerance_rel})`);
}

// -------------------------------------------------------------------- friction
{
  type Case = { preset: string; rpm: number; T_oil: number; T_coolant: number | null; fuel_mg: number;
    p_rail: number; grid_deg: number[]; p_cyl: number[]; engine: EngineView };
  const fx = load<{ cases: Case[] }, Record<string, number>[]>("friction");
  let worst = 0, where = "", evals = 0, ms = 0;
  fx.inputs.cases.forEach((c, i) => {
    const model = new FrictionModel(c.engine.spec, c.engine.cams);
    const oil = new Oil(c.engine.spec.oil, { ...c.engine.oil });
    const t0 = performance.now();
    const r = model.evaluate(c.grid_deg, c.p_cyl, c.rpm, oil, c.engine.wear, 1.05e5, c.fuel_mg, c.p_rail);
    ms += performance.now() - t0; evals++;
    for (const [k, want] of Object.entries(fx.outputs[i]!)) {
      const got = r[k];
      const rel = got === undefined ? Infinity : Math.abs(got - want) / Math.max(Math.abs(want), 1e-30);
      if (!(rel <= worst)) { worst = Number.isNaN(rel) ? Infinity : rel; where = `${c.preset} ${c.rpm} oil ${c.T_oil} K: ${k} (${got} vs ${want})`; }
    }
  });
  check("friction port matches Python (ADR-011)", worst <= fx.meta.tolerance_rel,
    `${fx.inputs.cases.length} cases x ${Object.keys(fx.outputs[0]!).length} quantities, worst rel ${worst.toExponential(2)}${where ? " at " + where : ""} ` +
    `(tolerance ${fx.meta.tolerance_rel}); ${(ms / evals).toFixed(1)} ms per evaluation of ${fx.inputs.cases[0]!.grid_deg.length} samples`);
}

const failed = results.filter(([, ok]) => !ok).length;
console.log(`\n${results.length - failed} passed, ${failed} failed`);
process.exit(failed ? 1 : 0);
