// Phase 4: the sound path's ports against fixtures/sound.json, generated by
// dieselsim (tools/fixtures/gen_fixtures.py, module "sound"). Blending is
// pure arithmetic on the stored cells, so it is held at 1e-12.
import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { Adr011Grid, SOURCE_KEYS, type Adr011GridData } from "../src/live/adr011.js";
import type { LiveSpec } from "../src/live/common.js";

/** fixtures.test.ts's definition (importing it would run that suite). */
function worstRel(got: readonly number[], want: readonly number[]): { rel: number; at: number } {
  if (got.length !== want.length) return { rel: Infinity, at: -1 };
  let big = 0;
  for (const w of want) big = Math.max(big, Math.abs(w));
  const floor = Math.max(1e-3 * big, 1e-300);
  let rel = 0, at = 0;
  for (let i = 0; i < want.length; i++) {
    const r = Math.abs(got[i]! - want[i]!) / Math.max(Math.abs(want[i]!), floor);
    if (Number.isNaN(r)) return { rel: Infinity, at: i };
    if (r > rel) { rel = r; at = i; }
  }
  return { rel, at };
}

const here = path.dirname(fileURLToPath(import.meta.url));
const fx = JSON.parse(readFileSync(path.resolve(here, "..", "..", "fixtures", "sound.json"), "utf8")) as {
  meta: { tolerance_rel: number; physics_hash: string };
  inputs: { spec: LiveSpec; grid: Adr011GridData; blend: [number, number, number][] };
  outputs: { blend: Record<string, number[] | Record<string, number>>[] };
};
const TOL = fx.meta.tolerance_rel;

let failed = 0, passed = 0;
const check = (name: string, ok: boolean, note = "") => {
  ok ? passed++ : failed++;
  console.log(`${ok ? "PASS" : "FAIL"}  ${name}${note ? "  -- " + note : ""}`);
};

const grid = new Adr011Grid(fx.inputs.spec, fx.inputs.grid);
fx.inputs.blend.forEach(([rpm, load, T], n) => {
  const got = grid.blendSources(rpm, load, T);
  const want = fx.outputs.blend[n]!;
  let worst = 0, where = "";
  for (const k of SOURCE_KEYS) {
    const r = worstRel(Array.from(got[k]), want[k] as number[]);
    if (r.rel > worst) { worst = r.rel; where = `${k}[${r.at}]`; }
  }
  const wm = want["_meta"] as Record<string, number>;
  const keys = Object.keys(wm);
  for (const k of keys) {
    const r = worstRel([got._meta[k]!], [wm[k]!]);
    if (r.rel > worst) { worst = r.rel; where = `_meta.${k}`; }
  }
  const sameKeys = keys.length === Object.keys(got._meta).length;
  check(`blend_sources at ${rpm} rpm, load ${load}, ${T} K`, worst <= TOL && sameKeys,
    `worst rel ${worst.toExponential(2)}${where ? " at " + where : ""} over ${SOURCE_KEYS.length} waveforms and ${keys.length} scalars (bound ${TOL})`);
});

// a grid built before Phase 4 has no sources: say so rather than return zeros
const bare = { ...fx.inputs.grid };
delete bare.src_f32; delete bare.src_cold_f32; delete bare.src_meta; delete bare.src_meta_cold;
let threw = false;
try { new Adr011Grid(fx.inputs.spec, bare).blendSources(1200, 0.5, 300); } catch { threw = true; }
check("a grid without sources refuses to blend them", threw);

console.log(`\n${passed} passed, ${failed} failed  (physics ${fx.meta.physics_hash.slice(0, 12)})`);
process.exit(failed ? 1 : 0);
