// GENERATED by `python3 tools/diag_torque_limiter.py --write-accuracy <pull output>`
// from a `--pull` run: each preset's full-load pull as this page solves it
// (fast path, n_cycles 9) against converged solves (real time, 200 cycles).
// Valid only for the physics build below; the page checks. FINDING-013.
export interface PresetAccuracy {
  /** worst relative torque error over positive-torque points, % (fast - converged) */
  worstPct: number;
  worstRpm: number;
  /** largest absolute difference where torque is negative (governed end), N.m */
  governedNm: number;
}

export const ACCURACY_PHYSICS = 'dd652e959dd31d1a5aa584428d4cc01533023611c9eb034822967f0dc1a2b0fd';

export const ACCURACY: Record<string, PresetAccuracy> = {
  crdi15: { worstPct: -5.8, worstRpm: 1650, governedNm: 2.0 },
  crdi_1p5: { worstPct: -8.3, worstRpm: 1200, governedNm: 20.1 },
  hd_i6: { worstPct: -2.8, worstRpm: 1950, governedNm: 10.5 },
  ld_i4: { worstPct: -3.8, worstRpm: 2600, governedNm: 5.1 },
  single: { worstPct: 0.0, worstRpm: 0, governedNm: 0.0 },
};
