// GENERATED by `python3 tools/diag_torque_limiter.py --write-accuracy <pull output>`
// from a `--pull` run: each preset's full-load pull as this page solves it
// (fast path, n_cycles 9) against converged solves (real time, 200 cycles).
// Valid only for the solver build below (bridge.grid_hash); the page checks. FINDING-013.
export interface PresetAccuracy {
  /** worst relative torque error over positive-torque points, % (fast - converged) */
  worstPct: number;
  worstRpm: number;
  /** largest absolute difference where torque is negative (governed end), N.m */
  governedNm: number;
}

export const ACCURACY_SOLVER = '0f1cc94cc4052f9597ed7996f0d8f0bb06ddd1635c04d0da054f3aa4edea1d0c';

export const ACCURACY: Record<string, PresetAccuracy> = {
  crdi15: { worstPct: -5.8, worstRpm: 1650, governedNm: 1.8 },
  crdi_1p5: { worstPct: -8.5, worstRpm: 1200, governedNm: 23.9 },
  hd_i6: { worstPct: -3.3, worstRpm: 1950, governedNm: 14.2 },
  ld_i4: { worstPct: -3.7, worstRpm: 2600, governedNm: 5.1 },
  single: { worstPct: 0.0, worstRpm: 0, governedNm: 0.0 },
};
